-- MySQL Script generated by MySQL Workbench
-- 05/31/17 21:53:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`station` ;

CREATE TABLE IF NOT EXISTS `mydb`.`station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`travel_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`travel_card` ;

CREATE TABLE IF NOT EXISTS `mydb`.`travel_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `count_of_trips` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time_of_purchase` DATETIME NOT NULL,
  `number_of_card` INT NOT NULL,
  `travel_card_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_travel_card1_idx` (`travel_card_id` ASC),
  INDEX `fk_ticket_station1_idx` (`station_id` ASC),
  CONSTRAINT `fk_ticket_travel_card1`
    FOREIGN KEY (`travel_card_id`)
    REFERENCES `mydb`.`travel_card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_station1`
    FOREIGN KEY (`station_id`)
    REFERENCES `mydb`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`trip` ;

CREATE TABLE IF NOT EXISTS `mydb`.`trip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time_of_trip` DATETIME NOT NULL,
  `ticket_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trip_ticket1_idx` (`ticket_id` ASC),
  INDEX `fk_trip_station1_idx` (`station_id` ASC),
  CONSTRAINT `fk_trip_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `mydb`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trip_station1`
    FOREIGN KEY (`station_id`)
    REFERENCES `mydb`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
